# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercardsavehistory',
            name='savemoney',
        ),
        migrations.RemoveField(
            model_name='customermoneycard',
            name='savemoney',
        ),
        migrations.AddField(
            model_name='customercardsavehistory',
            name='addmoney',
            field=models.FloatField(default=0, verbose_name=b'\xe6\x96\xb0\xe5\xa2\x9e\xe9\x87\x91\xe9\xa1\x8d'),
        ),
        migrations.AddField(
            model_name='customermoneycard',
            name='addmoney',
            field=models.FloatField(default=0, verbose_name=b'\xe6\x96\xb0\xe5\xa2\x9e\xe9\x87\x91\xe9\xa1\x8d'),
        ),
        migrations.AddField(
            model_name='customermoneycard',
            name='currentmoney',
            field=models.FloatField(default=0, verbose_name=b'\xe7\x9b\xae\xe5\x89\x8d\xe9\x87\x91\xe9\xa1\x8d'),
        ),
        migrations.AddField(
            model_name='customermoneycard',
            name='lastedmoney',
            field=models.FloatField(default=0, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe6\x96\xb0\xe5\xa2\x9e\xe9\x87\x91\xe9\xa1\x8d'),
        ),
    ]
