# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-20 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bean', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roastitem',
            options={'verbose_name': '\u70d8\u7119\u5496\u5561\u8c46', 'verbose_name_plural': '\u70d8\u7119\u5496\u5561\u8c46'},
        ),
    ]
