# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bean', '0002_auto_20170620_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginItemPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originprice', models.FloatField(default=0, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe9\x87\x91\xe9\xa1\x8d')),
                ('changedprice', models.FloatField(default=0, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe9\x87\x91\xe9\xa1\x8d')),
                ('createdtime', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\xbb\xba\xe7\xab\x8b\xe6\x99\x82\xe9\x96\x93')),
                ('originitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bean.OriginItem')),
            ],
            options={
                'verbose_name': '\u751f\u8c46\u50f9\u683c\u8b8a\u52d5\u7d00\u9304',
                'verbose_name_plural': '\u751f\u8c46\u50f9\u683c\u8b8a\u52d5\u7d00\u9304',
            },
        ),
        migrations.CreateModel(
            name='RoastItemPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originprice', models.FloatField(default=0, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe9\x87\x91\xe9\xa1\x8d')),
                ('changedprice', models.FloatField(default=0, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe9\x87\x91\xe9\xa1\x8d')),
                ('createdtime', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\xbb\xba\xe7\xab\x8b\xe6\x99\x82\xe9\x96\x93')),
                ('roastitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bean.RoastItem')),
            ],
            options={
                'verbose_name': '\u719f\u8c46\u50f9\u683c\u8b8a\u52d5\u7d00\u9304',
                'verbose_name_plural': '\u719f\u8c46\u50f9\u683c\u8b8a\u52d5\u7d00\u9304',
            },
        ),
    ]
