# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-30 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bean', '0003_originitempricehistory_roastitempricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='originitem',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 30, 2, 59, 46, 286890, tzinfo=utc), verbose_name=b'\xe5\xbb\xba\xe7\xab\x8b\xe6\x99\x82\xe9\x96\x93'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roastitem',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 30, 2, 59, 51, 137989, tzinfo=utc), verbose_name=b'\xe5\xbb\xba\xe7\xab\x8b\xe6\x99\x82\xe9\x96\x93'),
            preserve_default=False,
        ),
    ]
